version: '3.8'

services:
  hospital-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: hospital-frontend-app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
